create table products (
    id bigint generated by default as identity primary key,

    user_id uuid references auth.users(id) on delete cascade,

    name text not null,
    origin text not null,
    quantity integer not null default 0,
    supplier text not null,

    transport_time integer not null default 0,
    delivery_status text not null default 'Delivered'
);

alter table products enable row level security;

CREATE POLICY "Users can view own products"
ON products
FOR SELECT
USING (
  auth.uid() = user_id
);

CREATE POLICY "Users can insert own products"
ON products
FOR INSERT
WITH CHECK (
  auth.uid() = user_id
);

CREATE POLICY "Users can update own products"
ON products
FOR UPDATE
USING (
  auth.uid() = user_id
);

CREATE POLICY "Users can delete own products"
ON products
FOR DELETE
USING (
  auth.uid() = user_id
);

ALTER TABLE products
ADD CONSTRAINT quantity_positive
CHECK (quantity >= 0);

ALTER TABLE products
ADD CONSTRAINT transport_time_positive
CHECK (transport_time >= 0);